### ISSUE TITLE
Sorting is not saved

### ISSUE THREAD

**Issue by cboelter** [heimrichhannot/contao-multi-column-editor-bundle#10]
I'm trying to use the MultiColumnEditorBundle with the sorting function in the Contao Backend. The widget is configured like the following:

```
'profile'          => [
            'inputType' => 'multiColumnEditor',
            'eval'      => [
                'multiColumnEditor' => [
                    'sortable'            => true,
                    'minRowCount'         => 1,
                    'skipCopyValuesOnAdd' => true,
                    'fields'              => [
                        'network' => [
                            'label'     => &$GLOBALS['TL_LANG']['tl_ng_of_type']['profile_network'],
                            'inputType' => 'select',
                            'options'   => ['facebook', 'twitter', 'xing', 'linkedin', 'youtube', 'instagram', 'other'],
                            'eval'      => ['groupStyle' => 'width:350px'],
                        ],
                        'url'     => [
                            'label'     => &$GLOBALS['TL_LANG']['tl_ng_of_type']['profile_url'],
                            'inputType' => 'text',
                            'eval'      => ['groupStyle' => 'width:450px', 'rgxp' => 'url'],
                        ],
                    ],
                ],
            ],
            'sql'       => ['type' => 'blob', 'default' => 'null'],
        ],
```

I can use the drag handles, but it is not stored to the database. After a reload the sorting is as it was before the resorting. As I can see there should be an ajax call triggered on sorting. But the call isn't started. 
Do you have an ideo how i can get sorting working? :-)

**Comment by cboelter** [comment]
@heimrich-hannot would it help to sponsor the bugfix? :-)

**Comment by koertho** [comment]
@cboelter Hi, I can't reproduce this error. But I improved the asset handling in version 2.6. Please provide feedback if this may help. Also please always provide your contao version, your bundle version and your php version.

**Comment by koertho** [comment]
@cboelter Hi, we fixed a lot of issues like this in our last releases. Is this fixed for you now?
