### ISSUE TITLE
Comma missing in documentation

### ISSUE THREAD

**Issue by dakitec** [heimrichhannot/contao-multi-column-editor-bundle#11]
In the package documentation a comma is missing between the two elements. After the closing bracket `]` of field2 there need to be a comma.

`'field2' => [
                    'label' => 'field 2',
                    'inputType' => 'text',
                    'eval' => ['groupStyle' => 'width:150px']
                ]
                'field3' => [
                    'label' => 'field 3',
                    'inputType' => 'text',
                    'eval' => ['groupStyle' => 'width:150px']
                ]`

**Comment by koertho** [comment]
@dakitec Thanks for reporting!
