### ISSUE TITLE
Position bei Neues Feld hinzufügen

### ISSUE THREAD

**Issue by derMatze82** [heimrichhannot/contao-multi-column-editor-bundle#12]
Hallo,

wenn man über das Plus-Icon ein neues Feld hinzufügt, wird die neue Zeile manchmal oberhalb und manchmal oberhalb der aktuellen Zeile eingefügt. Ich erkenne da leider keine Logik. Besteht die Möglichkeit, dass die neue Zeile immer unter der Zeile eingefügt wird, auf der man auf das Plus-Icon geklickt hat?
Ich nutzer Version 2.10.0

Danke und liebe Grüße
Matze

**Comment by Defcon0** [comment]
Das hört sich nach einem Fehler an, denn eigentlich sollte es so funktionieren, dass die neue Row immer nach der Row platziert wird, wo das Plus geklickt wurde.

Kannst du uns bitte deinen DCA zur Verfügung stellen, da wir es nicht reproduziert bekommen. Danke dir!

**Comment by derMatze82** [comment]
Anbei das DCA:

`<?php
$GLOBALS['TL_DCA']['tl_content']['fields']['multilinks_max4'] = [
    'label'     => &$GLOBALS['TL_LANG']['tl_content']['multilinks'],
    'inputType' => 'multiColumnEditor',
    'eval'      => [
        'multiColumnEditor' => [

            'sortable' => true,
            'class' => 'multilinks',

            'minRowCount' => 0,

            'maxRowCount' => 4,

            'skipCopyValuesOnAdd' => true,

            'fields' => [
	            'multilinks_link' => [
	                'label'     => &$GLOBALS['TL_LANG']['MSC']['url'],
	                'exclude'   => true,
	                'inputType' => 'text',
	                'eval'      => [ 'groupStyle' => 'width:300px', 'mandatory' => true, 'rgxp' => 'url', 'decodeEntities'=>true, 'maxlength'=>255, 'dcaPicker'=>true, 'addWizardClass'=>false ]
	            ],
	            'multilinks_link_title' => [
	                'label'     => &$GLOBALS['TL_LANG']['tl_content']['multilinks_link_title'],
	                'exclude'   => true,
	                'inputType' => 'text',
	                'eval'      => [ 'groupStyle' => 'width:300px', 'mandatory' => true, 'maxlength'=>50 ]
	            ]
            ]
        ]
    ],
    'sql'       => "blob NULL"
];`

Wir verwenden Contao 4.10.0 (inkl. News, Kalender, etc.) ansonsten keine Erweiterungen.

Danke und liebe Grüße
Matze

**Comment by koertho** [comment]
@Defcon0 Konnte den Fehler gerade reproduzieren, fällt halt nie auf, wenn man skipCopyValuesOnAdd nicht auf true setzt.

**Comment by koertho** [comment]
@derMatze82 Das Problem sollte mit 2.10.2 gelöst sein. Würde mich über Feedback freuen!

**Comment by derMatze82** [comment]
@koertho funktioniert nun einwandfrei. Vielen Dank für eure Arbeit!
