### ISSUE TITLE
Tooltip for actions is wrong positioned or not initiated

### ISSUE THREAD

**Issue by rabauss** [heimrichhannot/contao-multi-column-editor-bundle#14]
**Context**
Contao version: 4.9.13
Bundle version: 2.12.2
PHP version: 7.4 (php8 not yet supported ;-))
Chrome: 89.0.4389.114 / Firefox: 87.0

**Description**

Sometimes the tooltip position is in the top left corner:
![image](https://user-images.githubusercontent.com/14016098/114309655-2cd24500-9ae8-11eb-9b00-4c53e40f7cf2.png)

Or it stays fixed at the icon position and wont toggle anymore. Even the tooltips of all other actions are not initiated anymore:
![image](https://user-images.githubusercontent.com/14016098/114309724-79b61b80-9ae8-11eb-97ae-7feb57d8d96b.png)

Same behavior in Firefox - although there the icon position with `align-self: end;` is interpreted different there!
![image](https://user-images.githubusercontent.com/14016098/114309878-0cef5100-9ae9-11eb-91d8-904bdb329cc0.png)

I think there is something like this missing:
https://github.com/menatwork/contao-multicolumnwizard-bundle/blob/e9594b1b2dbe3684100a8059fb2e99eed3ff2964/src/Resources/public/js/multicolumnwizard_be_src.js#L668-L675

**Comment by koertho** [comment]
@rabauss Thanks for reporting. We're already aware of this issue, but since this is just cosmetic, we didn't prioritized it.
But you're welcome to fix this in a PR :grin: 

P.S.: We met at the contao conference in Duisburg ;)

**Comment by rabauss** [comment]
Yes, you're right with the cosmetic, but it almost stopped me from using the extension.
I guess it has to be added somewhere in the `triggerAction` method:
https://github.com/heimrichhannot/contao-multi-column-editor-bundle/blob/master/src/Resources/npm-package/js/contao-multi-column-editor-bundle.js#L163

P.S. I know your business card is on my desk :blush:
