### ISSUE TITLE
Picker widgets throw errors because of wrong ID

### ISSUE THREAD

**Issue by rabauss** [heimrichhannot/contao-multi-column-editor-bundle#16]
**Context**
Contao version: 4.9.13
Bundle version: 
PHP version: 7.4

**Example DCA:**

````php
'multiColumnEditor' => [
    'sortable' => true,
    'minRowCount' => 0,
    'maxRowCount' => 0,
    'skipCopyValuesOnAdd' => true,
    'editorTemplate' => 'multi_column_editor_contao_palette',
    'palettes' => [
        'default' => 'page,file,link',
    ],
    'fields' => [
        'page' => [
            'label' => 'Page',
            'inputType' => 'pageTree',
        ],
        'file' => [
            'label' => 'File',
            'inputType' => 'fileTree',
            'eval' => [
                'fieldType' => 'checkbox',
                'filesOnly' => true,
                'extensions' => Config::get('validImageTypes'),
            ],
        ],
        'link' => [
            'label' => 'Link',
            'inputType' => 'picker',
            'eval' => ['context' => 'link'],
        ],
    ],
],
````

**Description**

Unfortunately the picker widgets throw the following error:
````js
Cannot read property 'fireEvent' of null
````

That's because of the inconsistent widget ID - on the one side `_0_` and on the other `[0]` 

The callback is generated by the widgets here:

https://github.com/contao/contao/blob/9107f939c444a31ff26252179497222b9e31424d/core-bundle/src/Resources/contao/widgets/PageTree.php#L232

https://github.com/contao/contao/blob/9107f939c444a31ff26252179497222b9e31424d/core-bundle/src/Resources/contao/widgets/FileTree.php#L374

https://github.com/contao/contao/blob/9107f939c444a31ff26252179497222b9e31424d/core-bundle/src/Resources/contao/widgets/Picker.php#L162

The link picker widget for the link even gets a `400 Bad Request` while reloading the picker!

I'm not sure if there has to be some special handling for the picker fields here:

https://github.com/heimrichhannot/contao-multi-column-editor-bundle/blob/0c9910989319af56a17e5f53735a2948aa6f412e/src/Widget/MultiColumnEditor.php#L554

**Comment by koertho** [comment]
Hi, thanks for reporting. We didn't used the picker widget so far. Someone will take a look into it.

**Comment by koertho** [comment]
This was a really tricky one, would love to hear if it works for you.

**Comment by rabauss** [comment]
I'm sorry, but with my example above it's not solved with Version 2.12.4.
Did you use a different DCA definition?

Currently, it's no use case for me - so I will not spend more time analyzing it, but the issue should not be closed 🙃

**Comment by koertho** [comment]
@rabauss Mhm...I used your dca snipped in an empty contao 4.9 instance in tl_article. Could you at least provide the error message?

**Comment by koertho** [comment]
This was the dca I used for testing.
```
$dca['fields']['someField'] = [
    'label'     => &$GLOBALS['TL_LANG']['tl_my_table']['someField'],
    'inputType' => 'multiColumnEditor',
    'exclude'   => true,
    'eval'      => [
        'multiColumnEditor' => [
            'sortable' => true,
            'minRowCount' => 0,
            'maxRowCount' => 0,
            'skipCopyValuesOnAdd' => true,
            'editorTemplate' => 'multi_column_editor_contao_palette',
            'palettes' => [
                'default' => 'page,file,link,text',
            ],
            'fields' => [
                'page' => [
                    'label' => 'Page',
                    'inputType' => 'pageTree',
                ],
                'file' => [
                    'label' => ['File','Some Label shit'],
                    'inputType' => 'fileTree',
                    'eval' => [
                        'fieldType' => 'checkbox',
                        'filesOnly' => true,
                        'extensions' => Config::get('validImageTypes'),
                    ],
                ],
                'link' => [
                    'label' => 'Link',
                    'inputType' => 'picker',
                    'eval' => ['context' => 'link'],
                ],
                'text' => [
                    'label' => ["Text", "Oh"],
                    'inputType' => 'text',
                ]
            ],
        ],
    ],
    'sql'       => "blob NULL"
];

PaletteManipulator::create()
    ->addField('linkPicker','inColumn', PaletteManipulator::POSITION_BEFORE)
    ->addField('someField','inColumn', PaletteManipulator::POSITION_BEFORE)
    ->applyToPalette('default', 'tl_article');
```

**Comment by koertho** [comment]
I'm closing this due inactivity.
