### ISSUE TITLE
New fields are not displayed for existing data.

### ISSUE THREAD

**Issue by raum51** [heimrichhannot/contao-multi-column-editor-bundle#20]
**Context**
Contao version: 4.13.4
Bundle version: 2.13.8
PHP version: 7.4.21

**Description**
If you change the DCA definition later (in the case of existing data), new fields will not be displayed for existing data records. And not only with the existing multi-column data sets of a table data set, but also with new multi-column data sets of a table data set that already has a multi-column data set.

Even changing the order of fields in the MultiColumn definition does not affect existing data.

**Comment by koertho** [comment]
@raum51 First question to ask: Did you clear your cache after changing your dca definition?

**Comment by raum51** [comment]
Hi @koertho! Thanks for your answer. Yes I cleared the cache and done it once more after your comment, with all possibilities that are mentioned in the Contao Manager:

```
vendor/bin/contao-console contao:maintenance-mode enable
rm -rf var/cache/prod
vendor/bin/contao-console cache:clear --no-warmup
vendor/bin/contao-console cache:warmup
vendor/bin/contao-console contao:maintenance-mode disable

vendor/bin/contao-console contao:maintenance-mode enable
rm -rf var/cache/dev
vendor/bin/contao-console cache:clear --no-warmup
vendor/bin/contao-console cache:warmup
vendor/bin/contao-console contao:maintenance-mode disable

vendor/bin/contao-console contao:maintenance-mode enable
rm -rf var/cache/prod
vendor/bin/contao-console cache:clear --no-warmup
rm -rf var/cache/prod
vendor/bin/contao-console contao:maintenance-mode disable

vendor/bin/contao-console contao:maintenance-mode enable
rm -rf var/cache/dev
vendor/bin/contao-console cache:clear --no-warmup
rm -rf var/cache/dev
vendor/bin/contao-console contao:maintenance-mode disable

composer clear-cache
```

But without any result: An existing multi-column data set doesn't show the new defined parameter. All complete new data sets from the corresponding tl-table show the new multi-column-parameter.

Maybe to be really clear my steps:

- defined a multi-column for an existing tl-table in the corresponding DCA definition
- clear the cache
- typed in some data into the before defined mutli-column
- added a new parameter to this multi-column in the DCA definition
- cleared the cache
- new parameter shows up in completely new data sets for this tl-table but not in already existing data sets of this tl-table that already contain data in this multi-column

**Comment by koertho** [comment]
Hi, I just tested this use case and it worked for me. Maybe is was fixed be an recent update. Or you forgot to add the field to the palette.
