### ISSUE TITLE
Installation unter Contao 5.2 fails

### ISSUE THREAD

**Issue by cmette** [heimrichhannot/contao-multi-column-editor-bundle#25]
Hello together
your composer.json of version 2.17.1 defines 

```
  "require": {
    "php": "^7.4 || ^8.0",
    "contao/core-bundle": "^4.9 || ^5.0",
```

but the installation under Contao 5.2.6 & PHP 8.1.10 fails. The bundle itself seems to be installable, but another constraint must be fullfilled: heimrichhannot/contao-utils-bundle is only released up to 4.13. 

Is this is a known limitation or an mistake?

The changelog.md says:
```
## [2.17.0] - 2023-10-31
- Added: support for contao 5
- Added: support for utils bundle v3

```

**Comment by koertho** [comment]
Maybe you have another dependency, that need contao-utils-bundle v2? Only v3 in compatible with contao 5

**Comment by cmette** [comment]
Thank you for your answer. I will test that straight away.

**Comment by cmette** [comment]
Ok, I have checked this briefly. If I comment out "heimrichhannot/contao-multi-column-editor-bundle", a composer update is possible. After that, I cannot find any dependency in the composer.lock on the contao-utils-bundle.

However, if I perform a composer update with require "heimrichhannot/contao-multi-column-editor-bundle" I get the following messages:

  Problem 1
    - heimrichhannot/contao-utils-bundle[2.222.0, ..., 2.232.0] require contao/core-bundle ^4.4 -> found contao/core-bundle[4.4.0, ..., 4.13.34], but it conflicts with the root package require composer.json (^5.1).
    - heimrichhannot/contao-multi-column-editor-bundle dev-master requires heimrichhannot/contao-utils-bundle ^2.225 || ^3.0-beta -> can be fulfilled by heimrichhannot/contao-utils-bun dle[2.225.0, ..., 2.232.0].
    - Root composer.json requires heimrichhannot/contao-multi-column-editor-bundle dev-master -> fulfilable by heimrichhannot/contao-multi-column-editor-bundle[dev-master].

I use my own fork (from yesterday evening) of the current bundle.

From my point of view, this dependency lies in the contao-multi-column-editor-bundle. 

Or have I overlooked something here?

**Comment by koertho** [comment]
@cmette Do you alle beta-dependencies in your root composer.json? utils-bundle v3 is currently only tagged as beta version, so this might be the problem. You could also require utils bundle v3 explicit in your root composer.json

**Comment by cmette** [comment]
Thank you! I've just found that out. I have it running now... We can close this Issue...
