### ISSUE TITLE
Dark Mode Support

### ISSUE THREAD

**Issue by ReneLuecking** [heimrichhannot/contao-multi-column-editor-bundle#26]
It would be nice to have dark mode support. I've achieved this in my own Contao installation by adding the following CSS rules which simply switch the fixed colors with available CSS variables:

```
.multi-column-editor-wrapper .multi-column-editor .rows,
.multi-column-editor-wrapper .multi-column-editor .rows.grouped > .mce-row {
    border-color: var(--content-border);
}

.multi-column-editor-wrapper .multi-column-editor .mce-row {
    background: var(--table-odd);
}

.multi-column-editor-wrapper .multi-column-editor .mce-row:nth-child(even) {
    background: var(--table-even);
}

.multi-column-editor-wrapper .multi-column-editor .mce-row:not(:last-child) {
    border-bottom-color: var(--content-border);
}

.multi-column-editor-wrapper .multi-column-editor .mce-row:focus,
.multi-column-editor-wrapper .multi-column-editor .mce-row:hover {
    background-color: var(--hover-row);
}
```

All the CSS variables are provided by the Contao Core itself  and Contao switches their values based on light/dark mode ([source](https://github.com/contao/core-bundle/blob/5.x/contao/themes/flexible/styles/basic.css)). All variables are available in Contao 4 and 5.

**Comment by koertho** [comment]
@ReneLuecking Hi, sorry for the late reply. You're welcome to do a PR request

**Comment by ReneLuecking** [comment]
See #27
