### ISSUE TITLE
Usage in backend subpalette

### ISSUE THREAD

**Issue by cboelter** [heimrichhannot/contao-multi-column-editor-bundle#3]
To use the Widget in a backend subpalette the javascript must be initialized after a palette change. I've added the following javascript for that:

`window.addEvent('ajax_change', function (event) {
    MultiColumnEditor.init();
});`

I think it would be nice to have it directly in the bundle.

**Comment by Defcon0** [comment]
In my case (Contao 4.4) `ajax_change`isn't called. Seems that this isn't a standard vanilla JS event. But in fact we have another solution (dynamic event listener adding). I'll upload a new version in no time.

**Comment by Defcon0** [comment]
OK, should be fixed in 1.2.2 of this bundle. Note that you also must update contao-utils-bundle to 2.67.1.
