### ISSUE TITLE
Darstellungsmodus `Kompakt` ergänzen?

### ISSUE THREAD

**Issue by OMOSde** [heimrichhannot/contao-multi-column-editor-bundle#31]
Ich nutze das Modul sehr gerne und meist nur für wenige Datensätze. Die Darstellung im Backend mit Label und Beschreibung für jeden Datenzeile erscheint oft sehr lang.

Ich behelfe mir daher mit dem Parameter `class` und mache die Darstellung per CSS kompakter.

Anbei mal ein Vergleich für 4 Datenzeilen.

![image](https://github.com/heimrichhannot/contao-multi-column-editor-bundle/assets/2035628/306f5410-df45-4d81-bca8-4e95b59dc946)
![image](https://github.com/heimrichhannot/contao-multi-column-editor-bundle/assets/2035628/faf6643f-069f-4ce0-9ab1-49ce91343103)

Vielleicht wäre dies etwas für eine Integration.

Mein CSS sieht so aus:

```
.multi-column-editor.compact .mce-row:not(:last-of-type) .tl_help,
.multi-column-editor.compact .mce-row:not(:first-of-type) h3 {
  display: none;
}

.multi-column-editor.compact .mce-row:not(:last-of-type) .form-group {
  margin-bottom: 0.125rem;
}
.multi-column-editor.compact .mce-row:not(:first-of-type) {
  padding-top: 0.125rem;
}
```

**Comment by koertho** [comment]
Hi, find ich eine super Idee. Habe es minimal anders in Version 2.20 integriert (siehe readme). Danke dir!
