### ISSUE TITLE
Verwendung in Subpalette führt zu Reload bei klick auf .add

### ISSUE THREAD

**Issue by cboelter** [heimrichhannot/contao-multi-column-editor-bundle#6]
Im Prinzip ein ähnliches Problem wie in diesem Ticket: https://github.com/heimrichhannot/contao-multi-column-editor-bundle/issues/3

Wenn ich das Widget in der aktuellen Version 2.4 in einer Subpalette verwende, greift das Javascript anscheinend nicht. Es wird jedes mal wenn ich auf den Button zum hinzufügen klicke ein Reload ausgelöst. Habt Ihr eine Idee woran das liegen könnte?

Meine Paketversionen:

`heimrichhannot-contao-components/sortablejs      1.8.4      sortablejs integration for Contao Open Source CMS
heimrichhannot/contao-ajax-bundle                1.0.7      Keep contao ajax requests organized and handle responses with ease.
heimrichhannot/contao-multi-column-editor-bundle 2.4.0      This module offers an input type for editing one or more records in fronten...
heimrichhannot/contao-multifileupload-bundle     1.2.1      Contao front end widget that provides dropzonejs.com functionality.
heimrichhannot/contao-request-bundle             1.0.8      A request class, that brings the symfony/http-foundation to contao.
heimrichhannot/contao-utils-bundle               2.127.0    This bundle offers various utility functionality for the Contao CMS.`

**Comment by Defcon0** [comment]
Könntest du bitte die neue Version 2.6.2 testen? Damit sollte es gehen. Kannst du das ganze bitte mal testen?
